version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: /devpi/logs/dp-info.log
    maxBytes: 10485760
    backupCount: 10
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: /devpi/logs/dp-error.log
    maxBytes: 10485760
    backupCount: 10
    encoding: utf8
root:
  level: INFO
  handlers: [info_file_handler, error_file_handler]
