#!/bin/bash
if [ ! -f /devpi/data/.__secrets ];
then
    touch /devpi/data/.__secrets
fi
if [ ! -f /devpi/data/.nodeinfo ];
then
    devpi-init \
        --role standalone \
        --serverdir /devpi/data \
        --storage sqlite
fi

trap /devpi/scripts/shutdown SIGHUP SIGINT SIGTERM TERM

startDevPiServerCmd=(devpi-server)
startDevPiServerCmd+=("--role")
startDevPiServerCmd+=("standalone")
startDevPiServerCmd+=("--host")
startDevPiServerCmd+=("0.0.0.0")
startDevPiServerCmd+=("--port")
startDevPiServerCmd+=("3141")
startDevPiServerCmd+=("--serverdir")
startDevPiServerCmd+=("/devpi/data")
startDevPiServerCmd+=("--storage")
startDevPiServerCmd+=("sqlite")
startDevPiServerCmd+=("--secretfile")
startDevPiServerCmd+=("/devpi/data/.__secrets")
startDevPiServerCmd+=("--restrict-modify")
startDevPiServerCmd+=("root")
startDevPiServerCmd+=("--logger-cfg")
startDevPiServerCmd+=("/devpi/logging.yaml")
startDevPiServerCmd+=("--absolute-urls")
startDevPiServerCmd+=("--start")

startNginXCmd="/etc/init.d/nginx start"

"${startDevPiServerCmd[@]}" & $startNginXCmd & wait
