#!/bin/bash
if [ "$1" != "" ];
then
    TEMPFILE="/devpi/backups/tmp_$1.tar.gz"
    FILE="/devpi/backups/$1.tar.gz"
    source /devpi/scripts/containerConfig

    $stopWebCmd

    cd /devpi
    tar -czf $TEMPFILE data
    rm -rf $FILE
    mv $TEMPFILE $FILE

    $startWebCmd
fi
